// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_events from "./routes/api/events.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_send_notifications from "./routes/api/send-notifications.ts";
import * as $api_subscribe from "./routes/api/subscribe.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $NotifyButton from "./islands/NotifyButton.tsx";
import * as $SearchForm from "./islands/SearchForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/events.ts": $api_events,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/send-notifications.ts": $api_send_notifications,
    "./routes/api/subscribe.ts": $api_subscribe,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/NotifyButton.tsx": $NotifyButton,
    "./islands/SearchForm.tsx": $SearchForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
